[package]
name = "gpu_editor"
version = "0.1.0"
edition = "2024"

[lib]
name = "gpu_editor"
path = "src/lib.rs"

[[bin]]
name = "gpu_editor"
path = "src/main.rs"

[dependencies]
ropey = "1.6.0"
winit = "0.29"
env_logger = "0.11"
log = "0.4"
wgpu = "0.19"
pollster = "0.3"
bytemuck = { version = "1.12", features = [ "derive" ] }
